### ISSUE TITLE
Error on frontend code

### ISSUE THREAD

**Issue by ramadis** [expo/image-upload-example#5]
in the file `frontend/main.js` on line 168, you try to get the MIME type from the URI. However, by doing `let fileType = uri[uri.length - 1];` you are only getting the uri's last character. To correctly get the MIME type you shoukd use `uriParts` instead of `uri`.

The line should be written as `let fileType = uriParts[uriParts.length - 1];`

**Comment by brentvatne** [comment]
fixed! thanks
