### ISSUE TITLE
Is it possible to use this example with firebase storage?

### ISSUE THREAD

**Issue by 20chix** [expo/image-upload-example#7]
I'm stuck into uploading the chosen picture with expo into firebase storage, I been trying for 16 hours but nothing. I used your example and it works as magic, but I need it for firebase storage.

**Comment by karimrdy** [comment]
hey @20chix,I'm stuck  like you,   did you found a way?

**Comment by 20chix** [comment]
I turned images into base64, and stored it into firebase.

**Comment by karimrdy** [comment]
i'tried that but didnt work, can you  give me  youre code. thank you

**Comment by brentvatne** [comment]
no
