### ISSUE TITLE
error in code?

### ISSUE THREAD

**Issue by jswhisperer** [expo/image-upload-example#9]
```
let uriParts = uri.split('.');
let fileType = uri[uri.length - 1];
```

should be

```
let uriParts = uri.split('.');
let fileType = uriParts[uriParts.length - 1];
```

**Comment by jswhisperer** [comment]
Also code doesn't send a POST anywhere right now

**Comment by brentvatne** [comment]
https://github.com/expo/image-upload-example/blob/master/frontend/App.js#L181-L191

?

**Comment by brentvatne** [comment]
ah I see what you mean re the first comment, fixed here: https://github.com/expo/image-upload-example/pull/11
